### ISSUE TITLE
Displaying test outputs in BehaveX for parallel runs

### ISSUE THREAD

**Issue by dron4ik86** [hrcorval/behavex#126]
Hi,
I've been running parallel tests using BehaveX and I noticed that the output in the console isn't showing the details of which test scenarios passed or failed. Normally, in Behave, the console output clearly lists each step of the scenarios along with their status, as shown below
```
@sanity
Scenario: Login Unhappy Flow - Invalid User Password             # features/tests/login_page/login_tests.feature:49
  Given Go to Login Page                                         # features/steps/login/login_steps.py:7
  And I generate a random email                                  # features/steps/login/login_steps.py:52
  And I generate a random password                               # features/steps/login/login_steps.py:59
  When I attempt to log in with the generated email and password # features/steps/login/login_steps.py:66
  Then I should see an error message "Wrong email or password."  # features/steps/login/login_steps.py:78
```
However, when running tests in parallel with BehaveX, this detailed step-by-step output is not displayed.

**Comment by hrcorval** [comment]
Hi @dron4ik86, You are right, the console output is not the same when running the tests in parallel. The reason for not doing that is that the information in console would be mixed while every parallel session prints something to console, making it unreadable. Instead of this, We are providing the other report formats (JUnit, HTML, JSON), that provides all the information as required.
