### ISSUE TITLE
Does not work with scenario outline

### ISSUE THREAD

**Issue by apetrenko-modus** [hrcorval/behavex#28]
Scenarios which were implemented as scenario outline were not executed. Their status in report is Automated Not Run

**Comment by hrcorval** [comment]
We did a fix in version 1.5.8. Please let us know if it doesn't work with that version and we will provide a fix asap. We are going to provide all necessary fixes to have a stable version

**Comment by hrcorval** [comment]
Issue already fixed and tested. You can try with version >=1.5.9

**Comment by apetrenko-modus** [comment]
Verified on 1.5.9. Not fixed. Still ignores Scenario outlines
<img width="1617" alt="image" src="https://user-images.githubusercontent.com/101675292/169657517-1113bd66-8799-4563-8b95-7a9dc04dfed0.png">

**Comment by hrcorval** [comment]
It seems there is somthing else we are not considering. Is it possible to share with me the tags you are using? If you can share the  feature file without the implementation files, removing any sensitive information, it will help us to reproduce and fix it. Thanks!!

**Comment by apetrenko-modus** [comment]
Ok. will prepare

**Comment by hrcorval** [comment]
We have been able to reproduce the issue. Basically, the bug arises when you add a description or name to the examples section:

--------------------------------------------
Scenario Outline: ......
Given .....
When .....
Then .....
Examples: <description> --> Bug is happening here
| <column_header> |
| <data>                   |
| <data>                   |
--------------------------------------------

Because of this, the wrapper is not parsing the scenarios as expected. As a workaround while this issue is being fixed, the description information should be removed and the tests will run accordingly.
We will tackle this bug asap. Thanks!

**Comment by venkat1993vcb** [comment]
Yes , as said by @apetrenko-modus unable to run parallely for Scenario Outline.

**Comment by hrcorval** [comment]
Thanks @venkat1993vcb for reporting it. Do you have a sample scenario that can help me on reproducing this issue?. Thanks!

**Comment by venkat1993vcb** [comment]
Normally the scenario outlines are running in parallel, but I'm trying to run two scenario outlines parallelly by adding values to the example table dynamically. One scenario outline will 116 scenarios , also i think the scenarios are running but the report is not generating properly. Please find the below image for reference.

![image](https://user-images.githubusercontent.com/82748439/170861342-12706da2-9e76-4525-8c1f-a004b3afdfca.png)

**Comment by hrcorval** [comment]
Hi @[venkat1993vcb](https://github.com/venkat1993vcb). I have been trying to reproduce the bug by dynamically adding examples to the table, but it seems the mechanism I'm using is not the same as in your implementation. TO be able to reproduce the error accordingly, can you please share a sample implementation on how you do to add examples to the table at runtime?
Thanks!

**Comment by writetomaha** [comment]
I am also facing this issue, unable to run the parallel execution for scenario outline.

**Comment by lazareviczoran** [comment]
Hi!

We also ran into this issue as we added the some scenario outlines. We are using version `1.6.0`. The way we ran the tests is by running `behavex --parallel-process 2` command, so it was using the default parallel-scheme (which is `scenario`).
That way the scenario outlines end up being skipped.

On the other hand, we noticed that when we tried to run `behavex --parallel-process 2 --parallel-scheme feature` all the scenario outlines have ran successfully, but this is not an ideal workaround since our feature files contain multiple scenarios that will run sequentually which can slow down the overall execution time, and we would want to have the scenario outlines running in parallel.

**Comment by hrcorval** [comment]
The parallel execution of scenario outlines has been fixed in latest versions, and this is a feature we are exhaustively using. We apologize for not getting this feature properly running in versions stated above. Latest version is working as expected.
Hope it helps!
