### ISSUE TITLE
Taking screenshot and attaching to report is not working

### ISSUE THREAD

**Issue by prsnth89** [hrcorval/behavex#36]
Hello,

Does anyone could help on taking screenshots and attaching to behavex auto generated html report?

My scenario is whenever a step gets failed i need to take screenshot and place it html report, currently i could take screenshot for each and every step but facing couple of issues

1) Should take screenshot only during failures [In java cucumber we have a method like step.isFailed() then take screenshot]
2) Screenshot image should be attached to report for the failed step

my environment.py is 

def after_step(context, step):
    print(step)
    print(f"----after step---")
    evidence_path = './output/outputs/logs/test.png'
    context.driver.save_screenshot(evidence_path)
    print("stored screenshot successfully"

My POC in python was successful along with this great plugin, i just got blocked with this issue alone, it would be very helpful if you could help on this

**Comment by hrcorval** [comment]
Hi @prsnth89, in order to store evidence as part of the HTML report, you should be able to use the following context variable:

> context.evidence_path

This variable is updated by the wrapper before executing each scenario, and all the files you copy into that path will be accessible from the HTML report, linked to the executed scenario

Also, in order to determine if the step has failed, you can check on the "step" variable that is set as input argument in "after_step(context, step)", by calling "step.status"

I hope it helps :)

**Comment by prsnth89** [comment]
Hi @hrcorval ,

Really thanks for your kind response, it worked for me :) Awesome report n kudos to your effort on building such a lovely plugin :)

**Comment by hrcorval** [comment]
Thanks a lot! I hope this module is useful for your testing purposes. If you like this module a lot it will be great if you can give it a star, just to start giving the repo more visibility. Thanks again :)
