### ISSUE TITLE
Picking wrong screenshot during parallel execution

### ISSUE THREAD

**Issue by prsnth89** [hrcorval/behavex#38]
Hi,

Good morninig!! Hope you are doing good!!

I have created an framework where i need to execute my test cases in parallel, here i am getting wrong screenshots in my output folder ie) Under both testcases i am getting one single screenshot file attached for both Login1 & Login2 feature

Login1.feature
     Examples
             | username       | password     |
             | standard_user1 | secret_sauce |
             | standard_user  | secret_sauce |
Login2.feature
      Examples
             | username          | password     |
             | standard_user2  | secret_sauce |
             | standard_user    | secret_sauce |

Note: Here below test cases should fail and respective screenshot should be published but i am getting same screenshot [standard_user1] in both file
           Login1.feature -->standard_user1
           Login2.feature -->standard_user2

Output
I have shared my demo project, please let me know if you could help on this 
https://github.com/prsnth89/PythonBehaveTest.git

**Comment by hrcorval** [comment]
Hi @prsnth89. Basically, the problem is that both scenarios have the same name ("Login with valid test1"), so the test execution results are being written to the same folder, as the evidence folders are created based on the scenario description.
I think that, as an improvement, the evidence_path should not take only in consideration the scenario description, but also the feature description 

Please, let me know if this helps.

**Comment by hrcorval** [comment]
https://github.com/hrcorval/behavex/issues/41

**Comment by prsnth89** [comment]
Hi @hrcorval  - Really thanks for your kind response, yes it worked fine without any issues after changing unique scenario name
