### ISSUE TITLE
UI tests do not run concurrently even when all required arguments are provided

### ISSUE THREAD

**Issue by IrynaIeremeichuk** [hrcorval/behavex#50]
My Behave framework uses Python 3.10 and behave 1.2.6

I have UI test in 1 feature file with 10 scenarios.

The command I run is:
behavex -t @{my_tag} --parallel-processes 10 --parallel-scheme scenario --no_capture -D browser=chrome -D vault_key={vault_key} -D project_path={project_path}

But still the scenarios are executed sequentially and not concurrently.
1 Chrome browser window opens at a time

**Comment by hrcorval** [comment]
Hi @IrynaIeremeichuk , we have been reviewing the implementation and we do not see the reason for the scenarios not to be running in parallel. Unless the scenarios are tagged with the @SERIAL tag, they should run in parallel.
One common problem is that only one instance of chrome browser can be opened at a time in a machine, so if you need to run your tests in parallel you need a multi-browser implementation like selenium grid, otherwise the other parallel session cannot continue until the session using the chrome browser finishes

Regards
