### ISSUE TITLE
Behavex exits almost instantly when running parallel processes for tags

### ISSUE THREAD

**Issue by EuanMor** [hrcorval/behavex#57]
I'm trying to use Behavex to concurrently execute several different feature files. To identify the feature files I want run, I've used tags. However, whenever I try to run Behavex it almost instantly exits (I don't even reach my before_all)

This is the command I am using: `behavex -texample -ttest --parallel-processes 2 --prarallel-scheme feature`
Where I have two separate feature files tagged with @example and @test respectively.
The problem only occurs when I specify more than 1 tag in the command.
E.g.  `behavex -texample --parallel-processes 2 --prarallel-scheme feature` runs fine for me.

I'm using Windows 10 with Python 3.10.0, behave 1.2.6 and behavex 1.6.0

**Comment by anibalinn** [comment]
Hi @EuanMor , basically the issue you are having is due to the logical implementation of tags:
`-texample -ttest` means that you will only execute the tests that have the `example` tag AND the `test` tag (this is a logical AND). So if the scenario does not have both tags it will not run. 
On the other hand, what you need is a logical OR, and this is done in the following way:
`-texample,test`
