### ISSUE TITLE
While running the test in parallel mode, it would have been nice if there are any tag which gets executed only once?

### ISSUE THREAD

**Issue by naseem6314** [hrcorval/behavex#68]
**Is your feature request related to a problem? Please describe.**
Right now we are running our test in parallel mode and we need to upload the installer once and share the installer ID with other threads. I have kept the code to upload the installer in the before_all method but the issue is that before_all gets triggered for every thread, every thread tries to upload the installer which sometimes results in an error and fails the code.

**Describe the solution you'd like**
I would love to have a method which gets executed only once before all the threads. I can use the same to upload the installer and share it with all the threads. Just like what we have in testNG before_suite

**Describe alternatives you've considered**
I tried handling using the code but it is not working. I tried the lock, synchronized method, and threading concept but it is still sharing.

**Additional context**
None

**Comment by hrcorval** [comment]
Hi @naseem6314, I understand your concern, as by design in each parallel process we are launching a new behave instance, so the scope of all hooks is related to each parallel session and the before_all hook might be executed multiple times.
We don't have an easy solution yet, but I think that as soon as figure it out an effective solution we will add it to our backlog and implement that.

Regards
